# Site settings
title: The Coast Range Reader
email: 
description: "Stories and ideas for west Oregonians."
baseurl: ""
url: "http://coastrangereader.github.io"
github_username: coastrangereader
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge